"""empty message

Revision ID: 0d455a0cc410
Revises: 153bda082f63
Create Date: 2019-02-08 18:54:47.441353

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d455a0cc410'
down_revision = '153bda082f63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=32), nullable=False))
    op.drop_column('users', 'register_time')
    op.drop_column('users', 'last_seen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('register_time', mysql.DATETIME(), nullable=True))
    op.drop_column('users', 'email')
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
