"""empty message

Revision ID: 1e9562a251d5
Revises: 7ea6610f6b1e
Create Date: 2019-03-06 20:31:53.457926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e9562a251d5'
down_revision = '7ea6610f6b1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('most_choice', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'most_choice')
    # ### end Alembic commands ###
