"""empty message

Revision ID: 3d4a8497586d
Revises: 76014a8725aa
Create Date: 2019-02-19 19:00:01.988103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d4a8497586d'
down_revision = '76014a8725aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('score', sa.Text(), nullable=True),
    sa.Column('class', sa.Integer(), nullable=True),
    sa.Column('col_1', sa.Integer(), nullable=True),
    sa.Column('col_2', sa.Integer(), nullable=True),
    sa.Column('col_3', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_test_id'), 'paper_test', ['id'], unique=False)
    op.add_column('users', sa.Column('paper_test_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'paper_test', ['paper_test_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'paper_test_id')
    op.drop_index(op.f('ix_paper_test_id'), table_name='paper_test')
    op.drop_table('paper_test')
    # ### end Alembic commands ###
