"""empty message

Revision ID: 76014a8725aa
Revises: 
Create Date: 2019-02-19 18:58:55.838131

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76014a8725aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_paper_test_id', table_name='paper_test')
    op.drop_table('paper_test')
    op.drop_column('users', 'paper_test_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('paper_test_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_table('paper_test',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('comment', mysql.TEXT(), nullable=True),
    sa.Column('score', mysql.TEXT(), nullable=True),
    sa.Column('class', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('col_1', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('col_2', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('col_3', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_paper_test_id', 'paper_test', ['id'], unique=False)
    # ### end Alembic commands ###
