"""empty message

Revision ID: 7ea6610f6b1e
Revises: 418a55c3d0e4
Create Date: 2019-03-05 21:12:33.064447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea6610f6b1e'
down_revision = '418a55c3d0e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('analyzed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grades', 'analyzed')
    # ### end Alembic commands ###
