"""empty message

Revision ID: 8ad981edd4a1
Revises: d19f164f4140
Create Date: 2019-02-20 20:28:58.427337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ad981edd4a1'
down_revision = 'd19f164f4140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('filename', sa.String(length=32), nullable=True))
    op.drop_column('papers', 'download_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('download_url', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column('papers', 'filename')
    # ### end Alembic commands ###
