"""empty message

Revision ID: b1c78474ccd9
Revises: ad87dea7191b
Create Date: 2019-02-17 20:21:11.924204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1c78474ccd9'
down_revision = 'ad87dea7191b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_infos', sa.Column('type', sa.String(length=32), nullable=True))
    op.alter_column('paper_infos', 'answers_score',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('paper_infos', 'comments',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('paper_infos', 'comments_condition',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('paper_infos', 'score_attr',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.drop_index('ix_paper_infos_table_name', table_name='paper_infos')
    op.create_index(op.f('ix_paper_infos_table_name'), 'paper_infos', ['table_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_infos_table_name'), table_name='paper_infos')
    op.create_index('ix_paper_infos_table_name', 'paper_infos', ['table_name'], unique=False)
    op.alter_column('paper_infos', 'score_attr',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('paper_infos', 'comments_condition',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('paper_infos', 'comments',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('paper_infos', 'answers_score',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_column('paper_infos', 'type')
    # ### end Alembic commands ###
