"""empty message

Revision ID: b2ac8557e639
Revises: 1c994b87ed50
Create Date: 2019-03-20 09:55:41.742174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2ac8557e639'
down_revision = '1c994b87ed50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('total_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grades', 'total_score')
    # ### end Alembic commands ###
