"""empty message

Revision ID: e90829f2f0a8
Revises: b1c78474ccd9
Create Date: 2019-02-18 21:09:31.990389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90829f2f0a8'
down_revision = 'b1c78474ccd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_infos', sa.Column('download_url', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_infos', 'download_url')
    # ### end Alembic commands ###
