"""empty message

Revision ID: ec3e5f5ad97c
Revises: 
Create Date: 2019-02-01 10:33:51.921445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec3e5f5ad97c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_infos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.String(length=32), nullable=False),
    sa.Column('paper_name', sa.String(length=32), nullable=False),
    sa.Column('cols_num', sa.Integer(), nullable=True),
    sa.Column('questions', sa.Text(), nullable=False),
    sa.Column('questions_img', sa.Text(), nullable=True),
    sa.Column('answers', sa.Text(), nullable=False),
    sa.Column('answers_img', sa.Text(), nullable=True),
    sa.Column('answers_score', sa.Text(), nullable=False),
    sa.Column('answers_multiple', sa.Text(), nullable=True),
    sa.Column('score_attr', sa.Text(), nullable=False),
    sa.Column('comments_condition', sa.Text(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'table_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'username'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('paper_infos')
    # ### end Alembic commands ###
