"""empty message

Revision ID: ecf8bba7ee40
Revises: ac492d9f1b6e
Create Date: 2019-03-04 12:22:49.960893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecf8bba7ee40'
down_revision = 'ac492d9f1b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('finished', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'finished')
    # ### end Alembic commands ###
