"""empty message

Revision ID: ff34e8d8aa41
Revises: fbfe767d87cb
Create Date: 2019-02-25 09:10:16.565563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff34e8d8aa41'
down_revision = 'fbfe767d87cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rb_users_papers_ibfk_2', 'rb_users_papers', type_='foreignkey')
    op.drop_constraint('rb_users_papers_ibfk_1', 'rb_users_papers', type_='foreignkey')
    op.create_foreign_key(None, 'rb_users_papers', 'papers', ['paper_id'], ['id'])
    op.create_foreign_key(None, 'rb_users_papers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rb_users_papers', type_='foreignkey')
    op.drop_constraint(None, 'rb_users_papers', type_='foreignkey')
    op.create_foreign_key('rb_users_papers_ibfk_1', 'rb_users_papers', 'papers', ['paper_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('rb_users_papers_ibfk_2', 'rb_users_papers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
